---
- name: Generate and download RSI and log files
  hosts: host_or_group
  connection: ansible.netcommon.network_cli
  gather_facts: no
  vars:
    ansible_network_os: junipernetworks.junos.junos
    ansible_command_timeout: 1800
    ansible_network_cli_ssh_type: paramiko

  tasks:
    - name: Request support information
      ansible.netcommon.cli_command:
        command: "request support information | save /var/tmp/{{ inventory_hostname }}-{{ '%Y-%m-%d' | strftime }}-rsi.txt"

    - name: Compress log files
      ansible.netcommon.cli_command:
        command: "file archive compress source /var/log/* destination /var/tmp/{{ inventory_hostname }}-{{ '%Y-%m-%d' | strftime }}-logs.tgz"

    - name: Download RSI and log files
      ansible.netcommon.net_get:
        src:
        - /var/tmp/{{ inventory_hostname }}-{{ '%Y-%m-%d' | strftime }}-rsi.txt
        - /var/tmp/{{ inventory_hostname }}-{{ '%Y-%m-%d' | strftime }}-logs.tgz
        dest: /tmp/
